name: Re-record cassettes

on:
  push:
    branches: [ main ]
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  rerecord:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Checkout sunpy core
        uses: actions/checkout@v3
        with:
          repository: dstansby/sunpy
          ref: vcrpy-testing

      - name: Run VCR tests
        run: |
          tox -e py310-vcr
          git rev-parse HEAD > cassettes/sunpy_core_sha.txt

      - name: Upload cassettes as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cassettes
          path: cassettes/

  # Note that the rerecord and upload workflows are split because the rerecord
  # workflow uses the sunpy/sunpy repository, and the upload workflow uses
  # the sunpy/sunpy-vcr-cassettes repository
  upload:
    runs-on: ubuntu-latest
    needs: rerecord
    steps:
      - name: Checkout previous cassettes
        uses: actions/checkout@v3

      - name: Download new casssetes
        uses: actions/download-artifact@v3
        with:
          name: cassettes
          path: ./cassettes

      - name: Check for modified cassettes
        id: check_modified
        run: |
          python -m pip install -r requirements.txt
          python check_new_files.py
          # Save exit code
          export MODIFIED=$?
          echo "::set-output name=modified_cassettes::$MODIFIED"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        # Only push changes if cassettes are modified
        if: steps.check_modified.outputs.modified_cassettes == 1
        with:
          commit_message: Update cassettes
          file_pattern: cassettes/*
